RDKCOM-1912: Amazon Prime - XDialServer Integration
rdkcentral/xdialserver pull request #7
Opened 2021-03-08 12:29 UTC by vaisakh806

Reason for change: XDial support for Amazon Prime required for pre-cert

Test Procedure: Refer ticket
Risks: None
Signed-off-by: Vaisakh Anand <vaisakh_anand@comcast.com>

2021-03-08 12:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/xdialserver?pullRequest=7) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/xdialserver?pullRequest=7) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/xdialserver?pullRequest=7) it.</sub>

2021-03-08 13:28 UTC, apatel859 submitted a review, later dismissed

2021-03-09 13:19 UTC, honglh requested changes

2021-03-09 13:19 UTC, honglh commented on server/main.c
> +    if (g_strstr_len(app_list_low, app_list_len, "amazon_prime")) {
can you use the reigstered DIAL app name in applist? E.g. "amazonInstantvideo"? This way we won't have naming conflicts and it will work well with future dynamic app list.

2021-03-09 13:19 UTC, honglh commented on server/main.c
> +  gdial_rest_server_register_app(dial_rest_server, "AmazonInstantVideo", NULL, TRUE, TRUE, allowed_origins);
the indentation should be aligned

2021-03-09 13:19 UTC, honglh commented on server/plat/gdial-plat-app.c
> +  else if (g_strcmp0(app_start_context->common.name, "AmazonInstantVideo") == 0) {
this change is not needed as async cb is not yet supported. When it it we will not have app names here

2021-03-10 11:58 UTC, vaisakh806 commented on server/main.c
> +    if (g_strstr_len(app_list_low, app_list_len, "amazon_prime")) {
@honglh ,  if I give "AmazonInstantVideo" with camel casing while running xdial, it will keep showing AmazonInstantVideo is not a registered app. The issue is that the app_list_low variable is a list of registered apps with names converted into lowercase in line 197. Hence using "AmazonInstantVideo" will require other changes as well, and I thought to keep the changes to a minimum for this integration.
    So, I will go ahead and use "amazoninstantvideo" for now and fix this review comment, however, if you need to bring any change over this please let me know.

2021-03-10 12:48 UTC, vaisakh806 commented on server/main.c
> +  gdial_rest_server_register_app(dial_rest_server, "AmazonInstantVideo", NULL, TRUE, TRUE, allowed_origins);
Sure I will get that done.

2021-03-10 12:49 UTC, vaisakh806 commented on server/plat/gdial-plat-app.c
> +  else if (g_strcmp0(app_start_context->common.name, "AmazonInstantVideo") == 0) {
Sure, I will remove it.

2021-03-10 21:02 UTC, honglh approved these changes

2021-03-12 10:38 UTC, apatel859 approved these changes

2021-03-13 23:46 UTC, merged